# Generated by Django 3.2.7 on 2021-09-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='direccion',
            new_name='apellidos',
        ),
    ]
